[workspace]
resolver = "3"
members = ["bin/ztreamerd", "crates/indexer", "crates/protocol", "crates/service"]

[workspace.dependencies]
zakura-chain = { git = "https://github.com/distractedm1nd/zakura.git", branch = "indexing" }
zakura-network = { git = "https://github.com/distractedm1nd/zakura.git", branch = "indexing" }
zakura-state = { git = "https://github.com/distractedm1nd/zakura.git", branch = "indexing" }
zakurad = { package = "zakura", git = "https://github.com/distractedm1nd/zakura.git", branch = "indexing", default-features = false }
