[package]
name = "ztreamer"
version = "0.1.0"
edition = "2024"

[dependencies]
heed = { version = "0.22.1", default-features = false }
prost = "0.14.4"
thiserror = "2"
tonic = "0.14.6"
tonic-prost = "0.14.6"
zakura-chain = { path = "../zakura/crates/zakura-chain" }
zakura-state = { path = "../zakura/crates/zakura-state", features = ["indexer"] }

[build-dependencies]
tonic-prost-build = "0.14.6"

[dev-dependencies]
hex = "0.4"
tempfile = "3"
